# Generated by Django 5.0.6 on 2024-05-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HockeyTeamsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=50)),
                ('awards', models.CharField(max_length=50)),
                ('losses', models.CharField(max_length=50)),
                ('win_percent', models.CharField(max_length=50)),
                ('goals_for', models.CharField(max_length=50)),
                ('goals_against', models.CharField(max_length=50)),
                ('plus_minus', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='ScrapedData',
            new_name='MoviesData',
        ),
    ]
