# Generated by Django 5.0.6 on 2024-05-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_hockeyteamsdata_rename_scrapeddata_moviesdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='hockeyteamsdata',
            name='wins',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
