# Generated by Django 5.0.6 on 2024-05-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0003_hockeyteamsdata_wins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hockeyteamsdata',
            name='awards',
        ),
    ]
