# Generated by Django 5.0.6 on 2024-05-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0004_remove_hockeyteamsdata_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesdata',
            name='year',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
